before_install:
  - sudo apt-get update
install:
  - sudo mkdir -p /etc/collectd/managed_config
  - sudo cp managed_config/* /etc/collectd/managed_config/
  - sudo mkdir -p /etc/collectd/filtering_config
  - sudo cp filtering_config/* /etc/collectd/filtering_config/
  - sudo cp collectd.conf /etc/collectd/collectd.conf
  - sudo cp signalfx_types_db /etc/collectd
  - sudo sed -i -e "s#/etc/collectd.d/#/etc/collectd/#" /etc/collectd/collectd.conf
  - sudo sed -i -e "s#/usr/share/collectd/types.db#/share/collectd/types.db#" /etc/collectd/collectd.conf
  - sudo find /etc/collectd/managed_config/ -type f | xargs sudo sed -i -e "s#/etc/collectd.d/#/etc/collectd/#"
  - sudo rm /etc/collectd/managed_config/10-innodb.conf
  - sudo apt-get -y update
  - sudo apt-get install -y wget
  - cd /tmp
  - wget http://collectd.org/files/collectd-5.4.1.tar.bz2
  - tar jxf collectd-5.4.1.tar.bz2
  - cd collectd-5.4.1
  - ./configure --prefix=/
  - sudo make all install
  - sudo cp /etc/collectd/collectd.conf /etc/collectd.conf
  - sudo touch /share/collectd/java/collectd-api.jar
  - sudo sed -i -e "s#/usr/share/collectd/java/collectd-api.jar#/share/collectd/java/collectd-api.jar#" /etc/collectd/managed_config/10-jmx.conf
  - sudo sed -i -e "s#/usr/share/collectd/java/generic-jmx.jar#/share/collectd/java/generic-jmx.jar#" /etc/collectd/managed_config/10-jmx.conf
# Currently the jmx plugin does not shutdown correctly.  Remove this when the bug is fixed?
  - sudo rm /etc/collectd/managed_config/10-jmx.conf
  - sudo collectd -h

# The -T exits with (1), so that sucks.
script: sudo collectd -t
